apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8smed
  namespace: k8smed-system
  labels:
    app.kubernetes.io/name: k8smed
    app.kubernetes.io/part-of: k8smed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8smed
  labels:
    app.kubernetes.io/name: k8smed
    app.kubernetes.io/part-of: k8smed
rules:
  # Allow K8sMed to read all resources
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "deployments", "services", "events", "nodes", "namespaces", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8smed
  labels:
    app.kubernetes.io/name: k8smed
    app.kubernetes.io/part-of: k8smed
subjects:
  - kind: ServiceAccount
    name: k8smed
    namespace: k8smed-system
roleRef:
  kind: ClusterRole
  name: k8smed
  apiGroup: rbac.authorization.k8s.io 