---
# Default state for all rules
default: true

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD024 - Multiple headings with the same content
MD024:
  allow_different_nesting: true

# MD029 - Ordered list item prefix
MD029:
  style: "one_or_ordered"

# MD033 - Inline HTML
MD033:
  allowed_elements:
    - "img"
    - "br"
    - "details"
    - "summary"

# MD041 - First line in a file should be a top-level heading
MD041:
  level: 1

# MD046 - Code block style
MD046:
  style: "fenced"

# Exclude vendored code and generated files
MD049: false
MD050: false 