name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

  release:
    name: Release
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This permission is needed for creating releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: Build release binaries
        run: make release

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: K8sMed ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            bin/release/kubectl-k8smed_linux_amd64
            bin/release/kubectl-k8smed_darwin_amd64
            bin/release/kubectl-k8smed_darwin_arm64
            bin/release/kubectl-k8smed_windows_amd64.exe
          body: |
            ## K8sMed ${{ env.VERSION }}
            
            See the [CHANGELOG](CHANGELOG.md) for details.
            
            ### Installation:
            
            #### Linux (amd64):
            ```
            curl -L https://github.com/k8smed/k8smed/releases/download/${{ env.VERSION }}/kubectl-k8smed_linux_amd64 -o kubectl-k8smed
            chmod +x kubectl-k8smed
            sudo mv kubectl-k8smed /usr/local/bin/
            ```
            
            #### macOS (Intel):
            ```
            curl -L https://github.com/k8smed/k8smed/releases/download/${{ env.VERSION }}/kubectl-k8smed_darwin_amd64 -o kubectl-k8smed
            chmod +x kubectl-k8smed
            sudo mv kubectl-k8smed /usr/local/bin/
            ```
            
            #### macOS (Apple Silicon):
            ```
            curl -L https://github.com/k8smed/k8smed/releases/download/${{ env.VERSION }}/kubectl-k8smed_darwin_arm64 -o kubectl-k8smed
            chmod +x kubectl-k8smed
            sudo mv kubectl-k8smed /usr/local/bin/
            ```
            
            #### Windows:
            Download `kubectl-k8smed_windows_amd64.exe`, rename it to `kubectl-k8smed.exe`, and add it to your PATH.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} 